image: nfcore/gitpod:latest

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:    
  - name: Download Nextflow Tutorial
    init: |
      echo 'init script' # runs during prebuild
      curl -s https://get.nextflow.io | bash
      curl -fsSL https://code.askimed.com/install/nf-test | bash
    command: |
      export PATH=/workspace/synteny:$PATH
      nextflow info
      unset JAVA_TOOL_OPTIONS
      echo 'Starting workspace !'
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
