name: Run Pipeline Tests

on:
  workflow_dispatch

env:
  NEXTFLOW_VERSION: 23.10.1
  NF_TEST_VERSION: 0.8.3

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clean workspace before start
      run: rm -rf $GITHUB_WORKSPACE/*

    - uses: actions/checkout@v4.1.1

    - name: Set up JDK 11
      uses: actions/setup-java@v4.0.0
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install nextflow
      run: sudo bash; cd /opt; wget "https://github.com/nextflow-io/nextflow/releases/download/v${NEXTFLOW_VERSION}/nextflow"; chmod +x nextflow;

    - name: Install nf-test
      run: sudo bash; cd /opt; wget "https://github.com/askimed/nf-test/releases/download/v${NF_TEST_VERSION}/nf-test-${NF_TEST_VERSION}.tar.gz"; tar -xvf "nf-test-${NF_TEST_VERSION}.tar.gz"; chmod +x nf-test; rm "/opt/nf-test-${NF_TEST_VERSION}.tar.gz"

    - name: Add software to path
      run: echo "/opt" >> $GITHUB_PATH;

    - name: Run ncbi_download test
      run: nf-test test tests/modules/download_ncbi.nf.test

    - name: Run gffread test
      run: nf-test test tests/modules/gffread.nf.test

    - name: Run jcvi test
      run: nf-test test tests/modules/jcvi.nf.test

    - name: download synteny test cds files
      run: cd data/synteny_input; wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1-sgGEBdkcDiw2XHwuapH53HCdzeil-F1' -O Drosophila_santomea.cds; wget --no-check-certificate 'https://docs.google.com/uc?export=download&id='1Sc8rD8ioxBJPIxZoCPkY_IkCBX1L_LwL -O Drosophila_simulans.cds 

    - name: Run synteny test
      run: nf-test test tests/modules/synteny.nf.test

    - name: Run chromopaint test
      run: nf-test test tests/modules/chromo.nf.test

    - name: Run score test
      run: nf-test test tests/modules/score.nf.test

    - name: Run score_tree test
      run: nf-test test tests/modules/score_tree.nf.test

    - name: Run go test
      run: nf-test test tests/modules/go.nf.test

    - name: Run go test
      run: nf-test test tests/modules/go_summarise.nf.test

    - name: Clean workspace after finish
      run: rm -rf $GITHUB_WORKSPACE/*
