name: Run Pipeline Tests

on:
  workflow_dispatch

env:
  NEXTFLOW_VERSION: 23.10.1
  NF_TEST_VERSION: 0.8.3

jobs:

  test_download:
       name: Run ncbi_download test
       runs-on: ubuntu-latest
       steps:
           - uses: actions/checkout@v4.1.1
           - uses: actions/setup-java@v4.0.0
             with:
               java-version: '17'
               distribution: 'adopt'
           - run: rm -rf $GITHUB_WORKSPACE/*
           - run: sudo bash; cd /opt; wget "https://github.com/nextflow-io/nextflow/releases/download/v${NEXTFLOW_VERSION}/nextflow"; chmod +x nextflow
           - run: sudo bash; cd /opt; wget "https://github.com/askimed/nf-test/releases/download/v${NF_TEST_VERSION}/nf-test-${NF_TEST_VERSION}.tar.gz"; tar -xvf "nf-test-${NF_TEST_VERSION}.tar.gz"; chmod +x nf-test; rm "/opt/nf-test-${NF_TEST_VERSION}.tar.gz"
           - run: echo "/opt" >> $GITHUB_PATH
           - run: nf-test test tests/modules/download_ncbi.nf.test

  test_gffread:
       name: Run gffread test
       runs-on: ubuntu-latest
       steps:
           - uses: actions/checkout@v4.1.1
           - uses: actions/setup-java@v4.0.0
             with:
               java-version: '17'
               distribution: 'adopt'
           - run: rm -rf $GITHUB_WORKSPACE/*
           - run: sudo bash; cd /opt; wget "https://github.com/nextflow-io/nextflow/releases/download/v${NEXTFLOW_VERSION}/nextflow"; chmod +x nextflow
           - run: sudo bash; cd /opt; wget "https://github.com/askimed/nf-test/releases/download/v${NF_TEST_VERSION}/nf-test-${NF_TEST_VERSION}.tar.gz"; tar -xvf "nf-test-${NF_TEST_VERSION}.tar.gz"; chmod +x nf-test; rm "/opt/nf-test-${NF_TEST_VERSION}.tar.gz"
           - run: echo "/opt" >> $GITHUB_PATH
           - run: nf-test test tests/modules/gffread.nf.test

  test_jcvi:
       name: Run jcvi test
       runs-on: ubuntu-latest
       steps:
           - uses: actions/checkout@v4.1.1
           - uses: actions/setup-java@v4.0.0
             with:
               java-version: '17'
               distribution: 'adopt'
           - run: rm -rf $GITHUB_WORKSPACE/*
           - run: sudo bash; cd /opt; wget "https://github.com/nextflow-io/nextflow/releases/download/v${NEXTFLOW_VERSION}/nextflow"; chmod +x nextflow
           - run: sudo bash; cd /opt; wget "https://github.com/askimed/nf-test/releases/download/v${NF_TEST_VERSION}/nf-test-${NF_TEST_VERSION}.tar.gz"; tar -xvf "nf-test-${NF_TEST_VERSION}.tar.gz"; chmod +x nf-test; rm "/opt/nf-test-${NF_TEST_VERSION}.tar.gz"
           - run: echo "/opt" >> $GITHUB_PATH
           - run: nf-test test tests/modules/jcvi.nf.test

  clean_finish:
       name: Clean workspace after finish
       needs: [test_download, test_gffread, test_jcvi]
       runs-on: ubuntu-latest
       steps:
           - uses: actions/checkout@v4.1.1
           - run: rm -rf $GITHUB_WORKSPACE/*
