name: Run Tests

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Install Nextflow v22.10.4
        run: |
          export NXF_VER=23.10.1
          curl -s https://get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
          curl -fsSL https://code.askimed.com/install/nf-test | bash
          sudo mv nf-test /usr/local/bin/

      - name: Test Pipeline
        run: |
          nf-test test tests/modules/download_ncbi.nf.test 
